#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
import time
import os 
from collections import namedtuple

loginprog = "/usr/sbin/console-shell"
loginprog_errno = 0

if len(sys.argv) > 1:
    loginprog_errno = 1
    loginprog = sys.argv[1]

if not os.path.exists(loginprog):
    loginprog_errno = 2

ROW_META = ('username','password','description','mail','level','locked','changepwdtime')
_Row = namedtuple("Row",ROW_META)

def Row(arr, tolerant =True):
    if not tolerant:
        return _Row(*arr)
    else:
        if len(arr) == len(ROW_META):
            pass
        elif len(arr) < len(ROW_META):
            arr.extend(['']*(len(ROW_META)-len(arr)))
        return _Row(*arr[:len(ROW_META)])

def validate_admin_passwd(username, password,split_char = ","):

    CONF_PATH = '/var/efw/userinfo/userslist'
    CONF_PATH_DEFAULT = '/var/efw/userinfo/default_userslist'

    if not os.path.exists(CONF_PATH):
        print "Fatal Error: admin config is not existed, will reset it !"
        if not os.path.exists(CONF_PATH_DEFAULT):
            print "Error: No userinfo!"
            return False
        else:
            os.system("cp %s %s"%(CONF_PATH_DEFAULT, CONF_PATH))

    with open(CONF_PATH) as fd:
        for line in fd:
            line = line.strip()
            if not line:
                continue

            meta = line.split(split_char)
            # print meta
            user = Row(meta)
            # print user
            if (user.locked != '0'):
                sys.stdout.write("This user has been locked\n")
                sys.stdout.flush()
                return False
            if (user.username == username and user.password == password):
                return True
    return False

def getpassword(maskchar = "*"):
    import tty
    import termios
    def getch():
        fd = sys.stdin.fileno()
    	sys.stdin.flush()
    	old_ttyinfo = termios.tcgetattr(fd)
    	try:
            tty.setraw(fd)
            ch = sys.stdin.read(1)
        finally:
            termios.tcsetattr(fd, termios.TCSADRAIN, old_ttyinfo)
        return ch
    
    passch = ""
    while True:
        ch = getch()
        # end of getpass
        if ch == "\r" or ch == "\n":
            sys.stdout.write("\n")
            sys.stdout.flush()
            return passch
        # Backspace
        elif ch == "\b" or ord(ch) == 127:
            if len(passch) > 0:
                sys.stdout.write("\b \b")
                sys.stdout.flush()
                passch = passch[:-1]
        else:
            if maskchar != "":
                sys.stdout.write(maskchar)
                sys.stdout.flush()
            passch += ch


def read(prompt = ""):
    in_put = raw_input(prompt).strip("\r\n")
    sys.stdout.flush()
    return in_put

def login():

    description = "login web user"

    username = ""
    password = ""
    failcount = 1

    while True:
 	# get username and password
    	sys.stdout.write("Login:")
        sys.stdout.flush()
        username = read()
        sys.stdout.write("Password:")
        sys.stdout.flush()
        password = getpassword("*")
    	# check user and password
        if (validate_admin_passwd(username, password)):
            break
        # log failcount
        if failcount > 3:
            return 
        failcount += 1
        time.sleep(2)
        sys.stdout.write("\033[31mauthorization failure\033[0m\n")
        sys.stdout.flush()
    
    os.system("clear")
    if loginprog_errno == 1:
        print sys.argv[1]
    elif loginprog_errno == 2:
        print "loginprog error, get /bin/bash"
        time.sleep(1)
        os.system("/bin/bash")
    os.system(loginprog)

login()

if __name__ == "__main()__":
    login()
